### ISSUE TITLE
Missing link in Roadmap

### ISSUE THREAD

**Issue by ttanay** [ververica/stateful-functions#10]
There's a missing link to a proposal in this line: "See this design proposal describing how Apache Flink and Apache Beam approach that problem."
https://github.com/ververica/stateful-functions/blob/master/stateful-functions-docs/docs/roadmap.rst#non-jvm-languages--polyglot-functions

This project is really cool! Looking forward to exploring and trying it out :)

**Comment by morsapaes** [comment]
Thanks for spotting the missing link, @ttanay! I've just added it in.

Also, feel free to reach out to us if you hit any barriers when giving the project a try!
