### ISSUE TITLE
 Filename too long error of :git clone https://github.com/ververica/stateful-functions.git

### ISSUE THREAD

**Issue by qingtiandalaoye** [ververica/stateful-functions#15]
git clone https://github.com/ververica/stateful-functions.git

Cloning into 'stateful-functions'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 1027 (delta 7), reused 6 (delta 6), pack-reused 1003
Receiving objects: 100% (1027/1027), 1.16 MiB | 51.00 KiB/s, done.
Resolving deltas: 100% (375/375), done.
**error: unable to create file stateful-functions-examples/stateful-functions-ridesharing-example/stateful-functions-ridesharing-example-simulator/src/main/java/com/ververica/statefun/examples/ridesharing/simulator/simulation/engine/DaemonThreadFactory.java: Filename too long**
Checking out files: 100% (447/447), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by igalshilman** [comment]
Hi @qingtiandalaoye,
I've just cloned it successfully on OSX and Ubuntu.

I've searched a bit  and found that this issue might come up on Windows [1], and it seems that the following command should solve it:
```
git config --system core.longpaths true
```

Good luck,
Igal.

[1] https://stackoverflow.com/a/22575737
