### ISSUE TITLE
ArtifactId of source sink dependency document miss "<"

### ISSUE THREAD

**Issue by SteNicholas** [ververica/stateful-functions#24]
Document description of source sink dependency is something wrong that lack of "<":
```
<artifactId>stateful-functions-flink-io/artifactId>
```
https://github.com/ververica/stateful-functions/blob/master/stateful-functions-docs/docs/api_concepts/io_module/source_sink.rst#dependency
@igalshilman

**Comment by sjwiesman** [comment]
Thank you for the PR and fixing this issue!
