### ISSUE TITLE
README class for usages of Harness is wrong

### ISSUE THREAD

**Issue by SteNicholas** [ververica/stateful-functions#26]
README description below is wrong：
- Take a look at the com.ververica.statefun.examples.harness.Main class to see example usages of Harness.
- Simply run the com.ververica.statefun.examples.harness.Main class.
https://github.com/ververica/stateful-functions/tree/master/stateful-functions-examples/stateful-functions-flink-harness-example#using-the-flink-harness-to-run-stateful-functions-applications-in-the-ide
@igalshilman

**Comment by sjwiesman** [comment]
Thank you for the PR and fixing this issue!
