### ISSUE TITLE
Unable to Deploy Greeter Example as a Flink Job

### ISSUE THREAD

**Issue by cdcsl** [ververica/stateful-functions#31]
Hi,

I've been trying to follow the deployment instructions for the greeter example.

In my pom.xml

> <dependencies>
    <dependencies>
        <dependency>
            <exclusions>
                <exclusion>  
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                    
                </exclusion>
                <exclusion>  
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                    
                </exclusion>
            </exclusions>
            <groupId>com.ververica</groupId>
            <artifactId>stateful-functions-flink-distribution</artifactId>
            <version>1.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.ververica</groupId>
            <artifactId>stateful-functions-sdk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ververica</groupId>
            <artifactId>stateful-functions-kafka-io</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.8.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
        </plugins>
    </build>

My Flink command

`~/flink-1.10-SNAPSHOT/bin/flink run -d -jar stateful-functions-greeter-example-1.1-SNAPSHOT-jar-with-dependencies.jar`

And the result

>  The program finished with the following exception:
org.apache.flink.client.program.ProgramInvocationException: Neither a 'Main-Class', nor a 'program-class' entry was found in the jar file.
	at org.apache.flink.client.program.PackagedProgram.getEntryPointClassNameFromJar(PackagedProgram.java:384)
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:148)
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:68)
	at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:590)
	at org.apache.flink.client.cli.CliFrontend.buildProgram(CliFrontend.java:726)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:203)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:933)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1006)
	at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1006)

Perhaps my build process is wrong. Any help would be appreciated.

Thanks.

**Comment by igalshilman** [comment]
Hi, to what Flink version are you trying to deploy?

The master branch works with (the unreleased) Flink 1.10-SNAPSHOT, if you are trying to submit to Flink 1.9 then I'd recommend using the release tag `v1.0.0`.

In addition, you can validate that the packing worked as expected by peaking into `stateful-functions-greeter-example-1.1-SNAPSHOT-jar-with-dependencies.jar`:

1. Make sure that the class that contains the main method for the stateful functions application is present, by running:
`jar tf stateful-functions-greeter-example-1.1-SNAPSHOT-jar-with-dependencies.jar | grep StatefulFunctionsJob.class`

2. Make sure that the main class is references at `META-INF/MANIFEST.MF`
By running:
`unzip -p  stateful-functions-greeter-example-1.1-SNAPSHOT-jar-with-dependencies.jar META-INF/MANIFEST.MF`

You should see:

```
...
Main-Class: com.ververica.statefun.flink.core.StatefulFunctionsJob
...
```

**Comment by cdcsl** [comment]
> Hi, to what Flink version are you trying to deploy?
> 
> The master branch works with (the unreleased) Flink 1.10-SNAPSHOT, if you are trying to submit to Flink 1.9 then I'd recommend using the release tag `v1.0.0`.
> 
> In addition, you can validate that the packing worked as expected by peaking into `stateful-functions-greeter-example-1.1-SNAPSHOT-jar-with-dependencies.jar`:
> 
> 1. Make sure that the class that contains the main method for the stateful functions application is present, by running:
>    `jar tf stateful-functions-greeter-example-1.1-SNAPSHOT-jar-with-dependencies.jar | grep StatefulFunctionsJob.class`
> 2. Make sure that the main class is references at `META-INF/MANIFEST.MF`
>    By running:
>    `unzip -p  stateful-functions-greeter-example-1.1-SNAPSHOT-jar-with-dependencies.jar META-INF/MANIFEST.MF`
> 
> You should see:
> 
> ```
> ...
> Main-Class: com.ververica.statefun.flink.core.StatefulFunctionsJob
> ...
> ```

Thanks for the response. I'm using Flink 1.10-SNAPSHOT.

My jar contains the main class, but my MANIFEST.MF is actually missing it. Adding the main class manually in my greeter pom.xml allows me to successfully load the JAR into Flink, but with further error

> java.lang.LinkageError: loader constraint violation: loader (instance of org/apache/flink/util/ChildFirstClassLoader) previously initiated loading for a different type with name "org/apache/kafka/clients/consumer/ConsumerRecord"

**Comment by igalshilman** [comment]
Can you please try creating the jar-with-dependices, with the `maven-shade-plugin` instead of the maven assembly plugin, you can use this:

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <!-- Run shade goal on package phase -->
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <artifactSet>
                                <excludes>
                                    <exclude>org.apache.flink:force-shading</exclude>
                                    <exclude>com.google.code.findbugs:jsr305</exclude>
                                    <exclude>org.slf4j:*</exclude>
                                    <exclude>log4j:*</exclude>
                                </excludes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    <!-- Do not copy the signatures in the META-INF folder.
                                    Otherwise, this might cause SecurityExceptions when using the JAR. -->
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>
                                        com.ververica.statefun.flink.core.StatefulFunctionsJob
                                    </mainClass>
                                </transformer>
                                <!-- required to aggregate all the META-INF/services files -->
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

(The source is [here](https://github.com/ververica/stateful-functions/blob/master/stateful-functions-flink/stateful-functions-flink-distribution/pom.xml#L95,L142))

**Comment by cdcsl** [comment]
Thanks, that fixed it. Should I be doing this for every deployment? I was under the impression that it would be done for me by including flink-distribution

> It includes all the runtime dependencies and configures the application's main entry-point. You do not need to take any action beyond adding the dependency to your Maven pom.

**Comment by igalshilman** [comment]
Glad it helped!

The flink-distribution artifact bundles all the necessary stateful functions classes and it must be in the class path. To achieve that you can either:
- include it in your `lib` directory of your Flink distribution once. 
- include it inside your  jar-with-dependencies. 

It seems to me that the maven assembly plugin wasn't configured properly in your case (the content of `assembly.xml`), while the maven-shade-plugin is configured properly.

In addition, there are some stateful functions specific configurations that needs to be present in your [`flink-conf.yaml`](https://github.com/ververica/stateful-functions/blob/master/tools/docker/flink-distribution-template/conf/flink-conf.yaml)
