### ISSUE TITLE
Time-to-live (TTL) for Functions

### ISSUE THREAD

**Issue by SteNicholas** [ververica/stateful-functions#32]
Does `Time-to-live (TTL) for Functions` of roadmap feature mean that to create `FunctionTtlConfig` supports automatically dropping function instances that have not been messaged for a defined amount of time, the way like `StateTtlConfig` of Flink, by default using `RocksdbCompactFilterCleanupStrategy`?

**Comment by igalshilman** [comment]
It means that, once enabled, function state that was not accessed would be TTLed. Can you share a little about your use case for function TTL?

**Comment by SteNicholas** [comment]
@igalshilman I haven't used the function TTL which includes in roadmap features. I just want to implement the TTL for functions feature. Therefore, I have confusion about this feature description.
