### ISSUE TITLE
The JsonModule and dynamic routing of proto messages

### ISSUE THREAD

**Issue by danp11** [ververica/stateful-functions#42]
Hi 

This is not an issue but I have looked into the JsonModule and its very nice to get rid
of the config in the code and instead specify the functions/ingresses/routers
in the yaml file. (The property consumer.group should be namned to group.id I guess)

Is there any work in progress to support "local" functions here as well, or do you have 
any plans/spec how this should be implemented? I'd be happy to try to implement this solution
if you have decided how it should look like.

When looking briefly in the code a thought is that "module:local" could have the property "functionProvider" and there one can specify for example  "com.ververica.statefun.examples.ridesharing.FunctionProvider"

Another thing I think would be good is to be able to specify several targets for
the ProtobufRouter. The router would then hold a map of <FunctionType, Address> och
loop thru it when sending downstream. To support the addressResolver to take several
attributes in the addressId i.e. "com.example/hello/{{$.name::$.surname}}" would IMO also
be a very nice addition and would make the routing config very dynamic.

Last thing :-) but I'm curious if there is a need to be able to replace attributes in 
other values than the addressId? (Example AddressResolver.multipleReplacements)
I did a very basic measurement of AddressResolver.evaluate with having FunctionType 
as an instance variable instead of this code:
  
  FunctionType functionType =
        new FunctionType(functionNamespace.evaluate(message), functionName.evaluate(message));

and it shortens the execution time by half, so it's quite an overhead.

Let me know if you think there is a use case for "JsonModule local with a StatefulFunctionProvider ", let addressResolver hold several address in ProtobufRouter and if it's possible to increase performance in method AddressResolver.evaluate. 

If yes, Id be happy to try to implement it :-)  

/Dan

**Comment by igalshilman** [comment]
Hi @danp11, and thank you for your interest in contributing to this project.
We are currently in the process of preparing the project for contribution to the Apache software foundation (see #43) and the development would continue as an Apache Flink subproject [statefun-flink](https://www.github.com/apache/flink-statefun).

The points raised in this issue are valid and valuable, and we can start the discussion for each item individually in the Apache way - mailing list, and the Apache JIRA with [STATEFUN] component.

Kind regards,
Igal.

**Comment by danp11** [comment]
Sounds good and Good work with the project so far!

Regards
Dan
