### ISSUE TITLE
could not find the repository of stateful-functions

### ISSUE THREAD

**Issue by shizhengchao** [ververica/stateful-functions#5]
there is no repository on maven, i can not get it
```xml
<dependency>
      <groupId>com.ververica</groupId>
      <artifactId>stateful-functions-flink-distribution</artifactId>
      <version>1.1-SNAPSHOT</version>
    </dependency>
```

**Comment by igalshilman** [comment]
Hello @shizhengchao !
You are correct, we did not yet publish the artifacts to maven central,
but you can build the project locally very easily, please follow the instructions here: https://github.com/ververica/stateful-functions#build
